FROM ubuntu:18.04

RUN echo "APT::Acquire::Retries \"5\";" > /etc/apt/apt.conf.d/80-retries

RUN apt-get -y update && apt-get install -y apt-utils
RUN apt-get install -y --fix-missing mc mingw-w64 yasm nasm gcc make cmake git pkg-config wget
    
###########

ENV BASE /FFmpeg
RUN mkdir $BASE
WORKDIR $BASE    

ENV https_proxy $http_proxy

RUN git clone --branch n4.2 --depth 1 https://github.com/FFmpeg/FFmpeg.git
RUN git clone --branch v1.8.1 --depth 1 https://chromium.googlesource.com/webm/libvpx
RUN git clone --depth 1 https://github.com/mirror/x264.git
RUN git clone --branch 3.1.1  --depth 1 https://github.com/videolan/x265.git
RUN git clone --branch v1.0.0-errata1 --depth 1 https://aomedia.googlesource.com/aom
RUN wget --retry-connrefused --tries=5 -nv http://downloads.xiph.org/releases/ogg/libogg-1.3.0.tar.gz && tar xzvf libogg-1.3.0.tar.gz
RUN wget --retry-connrefused --tries=5 -nv http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.3.tar.gz && tar xzvf libvorbis-1.3.3.tar.gz

ENV REL $BASE/release
ENV FREE_CONFIG --disable-all --enable-libvorbis --enable-libvpx --enable-libaom --enable-decoder=vp8,vp9,libaom_av1 --enable-encoder=libvpx_vp8,libvpx_vp9,libaom_av1 --enable-muxer=ogg,webm,matroska --enable-demuxer=ogg,webm,matroska --enable-bsf=vp9_superframe
ENV FULL_CONFIG --enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libvorbis --enable-libaom
ENV COMMON_CONFIG="--disable-static --enable-shared --disable-doc --enable-pic \
   --disable-programs \
   --disable-postproc --disable-avdevice --disable-swresample --disable-avfilter \
   --enable-version3 --enable-avcodec --enable-avformat --enable-swscale \
   --pkg-config-flags=--static \
   --pkg-config=pkg-config"

